name: Semantic Release

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Semantic Release
        run: npx semantic-release
